!--THIS ARTICLE IS WRITTEN IN ANSI（GB18030）--
!
!本程序向三种文件，两种方式输出Hello FORTRAN。因为gfortran不支持BINARY格式,这部分没有经编译验证
!
!编写时间：2014年12月16日，作者：王亮
OPEN (10,FILE='FS.txt' ,FORM='FORMATTED',ACCESS='SEQUENTIAL') 
WRITE(10,*)'Hello FORTRAN'
OPEN (11,FILE='FD.txt' ,FORM='FORMATTED',ACCESS='DIRECT',RECL=50) 
WRITE(11,'(A)',rec=1)'Hello FORTRAN'
OPEN(12,FILE='US.txt',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
WRITE(12)'Hello FORTRAN'
OPEN (13,FILE='UD.txt' ,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=50) 
WRITE(13,REC=1)'Hello FORTRAN'
OPEN (14,FILE='C.txt' ,FORM='BINARY',ACCESS='SEQUENTIAL') 
WRITE(14)'Hello FORTRAN'
OPEN (14,FILE='D.txt' ,FORM='BINARY',ACCESS='DIRECT',RECL=50) 
WRITE(14,REC=1)'Hello FORTRAN'
END
