SUBROUTINE LDLT(A,N,IW,P,IE)
IMPLICIT NONE
INTEGER::I,J,K,L,IL,IT,IJ,JL,MI,MJ
REAL::B
INTEGER,INTENT(IN)::N,IW
INTEGER,INTENT(OUT)::IE
REAL,INTENT(INOUT),DIMENSION(1:N,1:IW)::A
REAL,INTENT(INOUT),DIMENSION(1:N)::P
DO 15 I=1,N
IF(I.LE.IW) GOTO 20
IT=I-IW+1
GOTO 30
20 IT=1
30 K=I-1
IF(I.EQ.1) GOTO 40
DO 25 L=IT,K
IL=L+IW-I
B=A(I,IL)
A(I,IL)=B/A(L,IW)
P(I)=P(I)-A(I,IL)*P(L)
MI=L+1
DO 25 J=MI,I
IJ=J+IW-I
JL=L+IW-J
25 A(I,IJ)=A(I,IJ)-A(J,JL)*B
40 IF(A(I,IW).EQ.0.) GOTO 100
15 CONTINUE
DO 45 J=1,N
IF(J.LE.IW) GOTO 60
IT=N-J+IW
GOTO 70
60 IT=N
70 I=N-J+1
P(I)=P(I)/A(I,IW)
IF(J.EQ.1) GOTO 45
K=I+1
DO 65 MJ=K,IT
IJ=I-MJ+IW
65 P(I)=P(I)-P(MJ)*A(MJ,IJ)
45 CONTINUE
IE=0
GOTO 110
100 IE=1
110 RETURN
END
