SUBROUTINE MBW(NE,i3,IW)
IMPLICIT NONE
INTEGER::i,M
INTEGER,INTENT(IN)::NE
INTEGER,INTENT(OUT)::IW
INTEGER,INTENT(IN),DIMENSION(1:3,1:NE)::i3

IW=0
DO 10 i=1,NE
m=MAX(IABS(i3(1,i)-i3(2,i)),IABS(i3(2,i)-i3(3,i)),IABS(i3(3,i)-i3(1,i)))
IF(m+1.GT.IW) IW=m+1
10 CONTINUE
RETURN
END
