SUBROUTINE UB1(ND1,NB1,U1,ND,IW,SK,U)
IMPLICIT NONE
INTEGER::I,J
INTEGER,INTENT(IN)::ND1,ND,IW
INTEGER,INTENT(IN),DIMENSION(1:ND1)::NB1
REAL,INTENT(IN),DIMENSION(1:ND1)::U1
REAL,INTENT(OUT),DIMENSION(1:ND)::U
REAL,INTENT(INOUT),DIMENSION(1:ND,1:IW)::SK
DO 10 i=1,ND
10 U(I)=0
DO 20 I=1,ND1
J=NB1(I)
SK(J,IW)=SK(J,IW)*1.E10
20 U(J)=SK(J,IW)*U1(I)
RETURN
END
